# Generated by Django 3.2.6 on 2021-08-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
