# Generated by Django 3.2.6 on 2021-08-12 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('-id',), 'verbose_name': 'Заказчик', 'verbose_name_plural': 'Заказчик'},
        ),
    ]
