# Generated by Django 3.2.6 on 2021-08-12 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executors', '0002_executor_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executor',
            options={'ordering': ('-id',), 'verbose_name': 'Исполнитель', 'verbose_name_plural': 'Исполнитель'},
        ),
    ]
