# Generated by Django 3.2.6 on 2021-08-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='customer_or_freelancer',
            field=models.CharField(choices=[('Заказчик', 'Заказчик'), ('Фрилансер', 'Фрилансер')], max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Мужчина', 'Мужчина'), ('Женщина', 'Женщина'), ('Оно', 'Оно')], max_length=255),
        ),
    ]
