# Generated by Django 3.2.6 on 2021-08-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210812_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile',
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(default=0, verbose_name='Возраст:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Баланс:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Обо мне:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='customer_or_freelancer',
            field=models.CharField(choices=[('Заказчик', 'Заказчик'), ('Фрилансер', 'Фрилансер')], max_length=255, verbose_name='Выбор професии:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Мужчина', 'Мужчина'), ('Женщина', 'Женщина'), ('Оно', 'Оно')], max_length=255, verbose_name='Пол:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='Никнейм:'),
        ),
    ]
