# Generated by Django 3.2.6 on 2021-08-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Никнейм:')),
                ('bio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание:')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='Возраст:')),
                ('gender', models.CharField(choices=[('Мужчина', 'Мужчина'), ('Женщина', 'Женщина'), ('Оно', 'Оно')], max_length=255, verbose_name='Пол:')),
                ('balance', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчик',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Никнейм:')),
                ('bio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание:')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='Возраст:')),
                ('gender', models.CharField(choices=[('Мужчина', 'Мужчина'), ('Женщина', 'Женщина'), ('Оно', 'Оно')], max_length=255, verbose_name='Пол:')),
                ('balance', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Фрилансер',
                'verbose_name_plural': 'Фрилансер',
                'ordering': ('-id',),
            },
        ),
    ]
