# Generated by Django 3.2.6 on 2021-08-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customer_freelancer'),
        ('target', '0010_alter_task_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
