# Generated by Django 3.2.6 on 2021-08-15 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='balance',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='freelancer',
            old_name='balance',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='customer',
            new_name='from_account',
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.freelancer'),
            preserve_default=False,
        ),
    ]
